version: "3.5"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    networks:
      - sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ${DATA_ROOT}/sonarr/config:/config
      - ${MEDIA_ROOT}/Tv Shows:/tv
      - ${MEDIA_ROOT}/Downloads/Torrent:/downloads

networks:
  sonarr:
    name: sonarr
    driver: bridge
