version: "3.5"
services:
  guacamole:
    image: oznu/guacamole:armhf
    container_name: guacamole
    restart: unless-stopped
    networks:
      - guacamole
    ports:
      - 8082:8080
    volumes:
      - ${DATA_ROOT}/guacamole/config:/config

networks:
  guacamole:
    name: guacamole
    driver: bridge