version: "3.5"
services:
  pihole:
    image: pihole/pihole
    container_name: pihole
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.31.20
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ${DATA_ROOT}/pihole/etc-pihole:/etc/pihole
      - ${DATA_ROOT}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp6s18
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1
