version: "3.5"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    networks:
      - radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ${DATA_ROOT}/radarr/config:/config
      - ${MEDIA_ROOT}/Movies:/movies
      - ${MEDIA_ROOT}/Downloads/Torrent:/downloads

networks:
  radarr:
    name: radarr
    driver: bridge
