version: "3.5"
services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    restart: unless-stopped
    networks:
      dockervlan:
        ipv4_address: 192.168.31.20
    environment:
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT}/adguard/conf:/opt/adguardhome/conf
      - ${DATA_ROOT}/adguard/work:/opt/adguardhome/work

networks:
  dockervlan:
    name: dockervlan
    driver: macvlan
    driver_opts:
      parent: enp6s18
    ipam:
      config:
        - subnet: 192.168.31.0/24
          gateway: 192.168.31.1