version: "3.5"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    networks:
      - jackett
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - AUTO_UPDATE=true
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT}/jackett/config:/config
      - ${DATA_ROOT}/jackett/downloads:/downloads

networks:
  jackett:
    name: jackett
    driver: bridge