version: "3.5"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    networks:
      - portainer
    ports:
      - 9000:9000
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

networks:
  portainer:
    name: portainer
    driver: bridge

volumes:
  data: