version: "3.5"
services:
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    restart: unless-stopped
    networks:
      - bazarr
    ports:
      - 6767:6767
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    env_file:
      - .env
    volumes:
      - ${DATA_ROOT}/bazarr/config:/config
      - ${MEDIA_ROOT}/Movies:/movies
      - ${MEDIA_ROOT}/Tv Shows:/tv

networks:
  bazarr:
    name: bazarr
    driver: bridge