version: "3.5"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    restart: unless-stopped
    networks:
      - freshrss
    ports:
      - 8084:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
    volumes:
      - ${DATA_ROOT}/freshrss/config:/config

networks:
  freshrss:
    name: freshrss
    driver: bridge
