version: "3.5"
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    command:
      - '--collector.textfile.directory=/host/var/lib/node_exporter/textfile_collector'
    networks:
      - node-exporter
    ports:
      - 9100:9100
    environment:
      - TZ=Asia/Taipei
    volumes:
      - /:/host:ro,rslave

networks:
  node-exporter:
    name: node-exporter
    driver: bridge