version: "3.5"
services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    restart: unless-stopped
    networks:
      - wireguard
    ports:
      - 51820:${SERVERPORT}/udp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Taipei
      - SERVERURL=${SERVERURL}
      - SERVERPORT=${SERVERPORT}
      - PEERS=${PEERS}
      - PEERDNS=${PEERDNS}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET}
      - ALLOWEDIPS=${ALLOWEDIPS}
    volumes:
      - ${DATA_ROOT}/wireguard/config:/config
      - ${DATA_ROOT}/wireguard/modules:/lib/modules
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wireguard:
    name: wireguard
    driver: bridge