version: "3.5"
services:
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - redis
    ports:
      - 6379:6379
    volumes:
      - ${DATA_ROOT}/redis/conf:/usr/local/etc/redis/redis.conf
      - ${DATA_ROOT}/redis/data:/data

networks:
  redis:
    name: redis
    driver: bridge